os: linux
language: rust
cache: cargo
jobs:
  include:
    - rust: nightly-2020-03-19
      if: tag IS blank
      name: Linting (clippy)
      before_script:
        - rustup component add clippy
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy
