os: linux
language: rust
cache: cargo
jobs:
  include:
    - rust: nightly-2020-01-08
      name: Run cargo tests
      script:
        - cargo test --all-features
    - rust: nightly-2020-01-08
      name: Run cargo examples tests
      script:
        - bash test.sh
    - rust: nightly-2020-01-08
      if: tag IS blank
      env:
        - SHARD=lint
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy
        - cargo fmt -- --check
