os: linux
language: rust
cache: cargo
before_cache:
  - find target/debug -type f -maxdepth 1 -delete
  - rm -rf target/.rustc_info.json
  - rm -rf target/debug/incremental
jobs:
  include:
    - rust: nightly-2020-01-08
      name: Run cargo tests
      script:
        - cargo test --all-features -- --test-threads 1
    - rust: nightly-2020-01-08
      name: Run cargo examples tests
      script:
        - bash test.sh
    - rust: nightly-2020-01-08
      if: tag IS blank
      name: Linting (fmt + clippy)
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy
        - cargo fmt -- --check
