language: rust
cache: cargo
matrix:
  include:
    - rust: nightly-2020-01-08
      env:
        - SHARD=test
      script:
        - cargo test --all --all-features
    - rust: nightly
      if: tag IS blank
      env:
        - SHARD=lint
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --profile test
        - cargo fmt -- --check
