language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
env:
  - PATH=$HOME/.cargo/bin:$PATH
script:
  - cargo test --all --tests
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # Run Clippy in its own shard.
    - rust: nightly
      env:
        - SHARD=clippy
      before_script:
        - rustup component add --toolchain nightly clippy
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --profile test
