[package]
name = "reign"
version = "0.2.1"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Opinionated Fullstack Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["fullstack", "web", "framework", "reign"]
categories = []
license = "MIT OR Apache-2.0"
readme = "README.md"
autoexamples = false

[[bin]]
name = "reign"
path = "src/cli/main.rs"
required-features = ["cli"] # remove the need for this

[lib]
name = "reign"
path = "src/lib.rs"

[dependencies]
# lib deps
reign_boot = { path = "./reign_boot", version = "0.2.0", optional = true }
reign_derive = { path = "./reign_derive", version = "0.2.0", optional = true }
reign_router = { path = "./reign_router", version = "0.2.0", optional = true }
reign_view = { path = "./reign_view", version = "0.2.0", optional = true }

# cli deps
clap = { version = "3.0.0-beta.1", optional = true }
handlebars = { version = "3.1.0", optional = true }
serde = { version = "1.0.110", optional = true, features = ["derive"] }
serde_json = { version = "1.0.53", optional = true }
Inflector = { version = "0.11.4", optional = true }
console = { version = "0.11.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }
thiserror = { version = "1.0.19", optional = true }

[dev-dependencies]
version-sync = "0.9.0"

[workspace]
members = [
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",

	"examples/*",
]
default-members = [
	".",
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",
]

[features]
default = ["view-backend", "framework"]
cli = ["clap", "handlebars", "serde", "serde_json", "Inflector", "console", "lazy_static", "thiserror"]
doc = []
framework = ["reign_boot"]
view = ["reign_view", "reign_derive/view"]
router-backend = ["reign_router", "reign_derive/router-backend"]
view-backend = ["reign_view/view-backend", "reign_derive/view-backend", "view", "router-backend"]
session-redis = ["reign_router/session-redis", "router-backend"]
file-handlers = ["reign_router/file-handlers", "router-backend"]

[package.metadata.docs.rs]
all-features = true
