[package]
name = "reign"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Opinionated Fullstack Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["fullstack", "web", "framework", "reign"]
categories = []
license = "MIT OR Apache-2.0"
readme = "README.md"
autoexamples = false

[[bin]]
name = "reign"
path = "src/cli/main.rs"
required-features = ["cli"] # remove the need for this

[lib]
name = "reign"
path = "src/lib.rs"

[dependencies]
# lib deps
reign_boot = { path = "./reign_boot", version = "0.1.2", optional = true }
reign_derive = { path = "./reign_derive", version = "0.1.2", optional = true }
reign_router = { path = "./reign_router", version = "0.1.2", optional = true }
reign_view = { path = "./reign_view", version = "0.1.2", optional = true }

# cli deps
clap = { version = "3.0.0-beta.1", optional = true }

[dev-dependencies]
version-sync = "0.9.0"

[workspace]
members = [
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",

	"examples/*",
]
default-members = [
	".",
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",
]

[features]
default = ["view-backend", "framework"]
cli = ["clap"]
doc = []
framework = ["reign_boot"]
view = ["reign_view", "reign_derive/view"]
router = ["reign_router", "reign_derive/router"]
view-backend = ["reign_view/view-backend", "reign_derive/view-backend", "view", "router"]
session-redis = ["reign_router/session-redis"]
file-handlers = ["reign_router/file-handlers"]

[package.metadata.docs.rs]
all-features = true
