[package]
name = "reign"
version = "0.1.1"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[[bin]]
name = "reign"
path = "src/main.rs"

[lib]
name = "reign"
path = "src/lib.rs"

[dependencies]
reign_boot = { path = "./reign_boot", version = "0.1.1" }
reign_derive = { path = "./reign_derive", version = "0.1.1" }
reign_view = { path = "./reign_view", version = "0.1.1" }
log = "0.4.8"

[dev-dependencies]

[workspace]
members = [
	"reign_boot",
	"reign_derive",
	"reign_view",
]
