[package]
name = "reign"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[[bin]]
name = "reign"
path = "src/main.rs"
required-features = ["build-binary"]

[lib]
name = "reign"
path = "src/lib.rs"

[dependencies]
reign_boot = { path = "./reign_boot", version = "0.1.2", optional = true }
reign_derive = { path = "./reign_derive", version = "0.1.2" }
reign_router = { path = "./reign_router", version = "0.1.2", optional = true }
reign_view = { path = "./reign_view", version = "0.1.2" }
log = "0.4.8"
structopt = { version = "0.3.7", optional = true }

[dev-dependencies]
version-sync = "0.8"

[workspace]
members = [
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",

	"examples/full/basic",

	"examples/router/actix",
	"examples/router/gotham",
	"examples/router/tide",

	"examples/views/normal",
	"examples/views/actix",
	"examples/views/gotham",
	"examples/views/tide",
	"examples/views/warp",
]
default-members = [
	".",
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",
]

[features]
default = ["views-gotham", "router-gotham", "framework", "helpers-redirect"]
framework = ["reign_boot"]
build-binary = ["structopt"]
build-docs = []
views-actix = ["reign_view/views-actix", "reign_derive/views-actix"]
views-gotham = ["reign_view/views-gotham", "reign_derive/views-gotham"]
views-tide = ["reign_view/views-tide", "reign_derive/views-tide"]
views-warp = ["reign_view/views-warp", "reign_derive/views-warp"]
helpers-redirect = ["reign_view/helpers-redirect", "reign_derive/helpers-redirect"]
router = []
router-actix = ["reign_router/router-actix", "reign_derive/router-actix", "router"]
router-gotham = ["reign_router/router-gotham", "reign_derive/router-gotham", "router"]
router-tide  = ["reign_router/router-tide", "reign_derive/router-tide", "router"]

[package.metadata.docs.rs]
all-features = true
