[package]
name = "reign"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[[bin]]
name = "reign"
path = "src/main.rs"
required-features = ["build-binary"]

[lib]
name = "reign"
path = "src/lib.rs"

[dependencies]
reign_boot = { path = "./reign_boot", version = "0.1.2" }
reign_derive = { path = "./reign_derive", version = "0.1.2" }
reign_router = { path = "./reign_router", version = "0.1.2" }
reign_view = { path = "./reign_view", version = "0.1.2" }
log = "0.4.8"
structopt = { version = "0.3.7", optional = true }

[dev-dependencies]

[workspace]
members = [
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",

	"examples/basic",
	# "examples/views/actix",
	"examples/views/gotham",
	"examples/views/normal",
	"examples/views/tide",
	"examples/views/warp",
]
default-members = [
	".",
	"reign_boot",
	"reign_derive",
	"reign_router",
	"reign_view",
]

[features]
default = ["views-gotham", "router-gotham"]
build-binary = ["structopt"]
views-gotham = ["reign_view/views-gotham", "reign_derive/views-gotham"]
views-warp = ["reign_view/views-warp", "reign_derive/views-warp"]
views-tide = ["reign_view/views-tide", "reign_derive/views-tide"]
views-actix = ["reign_view/views-actix", "reign_derive/views-actix"]
router-gotham = ["reign_router/router-gotham", "reign_derive/router-gotham"]
