[package]
name = "{{ name }}"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
reign = { version = "{{ reign_version }}", features = ["file-handlers"] }
tokio = { version = "0.2.21", features = ["full"] }
thiserror = "1.0.19"
serde = { version = "1.0.110", features = ["derive"] }
