[package]
name = "reign_boot"
version = "0.1.1"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[lib]
name = "reign_boot"
path = "src/lib.rs"

[dependencies]
dotenv = "0.15.0"

[dev-dependencies]
