[package]
name = "reign_derive"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro-error = "0.4"
proc-macro2 = "1"
regex = "1.3.1"
reign_view = { path = "../reign_view", version = "0.1.2" }
Inflector = "0.11.4"
lazy_static = "1.4.0"

[dev-dependencies]
reign = { path = "../" }

[features]
default = []
views-actix = ["reign_view/views-actix"]
views-gotham = ["reign_view/views-gotham"]
views-tide = ["reign_view/views-tide"]
views-warp = ["reign_view/views-warp"]
router-gotham = []
