[package]
name = "examples_router_warp"
version = "0.0.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../reign", features = ["router-warp"], default-features = false }
warp = "0.2.2"
tokio = { version = "0.2.21", features = ["full"] }
anyhow = "1.0.31"
thiserror = "1.0.19"
serde_json = "1.0.53"
regex = "1.3"

[dev-dependencies]
test_examples = { path = "../../../reign/development/test_examples" }
