[package]
name = "reign_router"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Opinionated Fullstack Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["fullstack", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[lib]
name = "reign_router"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.11"
hyper = "0.13.5"
url = "2.1.1"
mime = "0.3.16"
futures = "0.3.5"
tokio = "0.2.21"
log = "0.4.8"
thiserror = "1.0.19"
anyhow = "1.0.31"
regex = "1.3.9"
percent-encoding = "2.1.0"

[dev-dependencies]
reign = { path = "../" }
version-sync = "0.9.0"
tokio = { version = "0.2.21", features = ["full"] }
reqwest = "0.10.4"

[features]
default = []
doc = []

[package.metadata.docs.rs]
all-features = true
