[package]
name = "reign_view"
version = "0.1.2"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[lib]
name = "reign_view"
path = "src/lib.rs"

[dependencies]
gotham = "0.4.0"
hyper = "0.12.32"
mime = "0.3.14"
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
regex = "1.3.1"
Inflector = "0.11.4"

[dev-dependencies]
reign = { path = "../" }
pretty_assertions = "0.6.1"
