[package]
name = "reign_view"
version = "0.1.2" # Also change html_root_url in lib.rs
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"
exclude = ["src/views"]

[lib]
name = "reign_view"
path = "src/lib.rs"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
regex = "1.3.1"
Inflector = "0.11.4"
maplit = "1.0.2"
mime = { version = "0.3", optional = true }
actix-web = { version = "2.0", optional = true }
gotham = { git = "git://github.com/gotham-rs/gotham", branch = "master", optional = true }
tide = { version = "0.6", optional = true }
warp = { version = "0.2", optional = true }

[dev-dependencies]
reign = { path = "../" }
pretty_assertions = "0.6"
version-sync = "0.8"
actix-rt = "1.0"
tokio = "0.2"
reqwest = "0.10"

[features]
default = []
build-docs = []
views-actix = ["actix-web", "mime"]
views-gotham = ["gotham", "mime"]
views-tide = ["tide", "mime"]
views-warp = ["warp", "mime"]

[package.metadata.docs.rs]
all-features = true
