[package]
name = "reign_view"
version = "0.1.2" # Also change html_root_url in lib.rs
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Isomorphic Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["isomorphic", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"
exclude = ["src/views"]

[lib]
name = "reign_view"
path = "src/lib.rs"

[dependencies]
gotham = { git = "git://github.com/reign-rs/gotham", branch = "hyper-export", optional = true }
mime = { version = "0.3.14", optional = true }
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
regex = "1.3.1"
Inflector = "0.11.4"
maplit = "1.0.2"

[dev-dependencies]
reign = { path = "../" }
pretty_assertions = "0.6.1"

[features]
default = []
views-gotham = ["gotham", "mime"]
views-warp = []

[package.metadata.docs.rs]
all-features = true
