[package]
name = "reign_router"
version = "0.2.1"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Opinionated Fullstack Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["fullstack", "web", "framework", "reign", "router"]
categories = ["web-programming"]
license = "MIT"
readme = "README.md"

[lib]
name = "reign_router"
path = "src/lib.rs"

[dependencies]
url = "2.1.1"
mime = "0.3.16"
hyper = "0.13.5"
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["io-util"] }
log = "0.4.8"
thiserror = "1.0.19"
anyhow = "1.0.31"
chrono = "0.4.19"
regex = "1.3.9"
percent-encoding = "2.1.0"
paste = "1.0.2"
# TODO: No need for package renaming after https://github.com/rust-lang/cargo/issues/5565
cookie_r = { package = "cookie", version = "0.14.0", features = [], optional = true }
serde =  { version = "1.0.110", optional = true }
bincode =  { version = "1.2.1", optional = true }
rand =  { version = "0.7.3", optional = true }
rand_chacha =  { version = "0.2.2", optional = true }
base64 =  { version = "0.12.1", optional = true }

[dev-dependencies]
reign = { path = "../" }
version-sync = "0.9.0"
tokio = { version = "0.2.21", features = ["macros"] }
reqwest = "0.10.4"

[features]
default = []
doc = []
cookie = ["cookie_r"]
session = ["cookie", "serde", "bincode", "rand", "rand_chacha", "base64"]

[package.metadata.docs.rs]
all-features = true
