[package]
name = "reign_router"
version = "0.2.1"
authors = [
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
edition = "2018"
description = "Opinionated Fullstack Web Framework in Rust"
repository = "https://github.com/pksunkara/reign"
keywords = ["fullstack", "web", "framework", "reign"]
categories = []
license = "MIT"
readme = "README.md"

[lib]
name = "reign_router"
path = "src/lib.rs"

[dependencies]
url = "2.1.1"
mime = "0.3.16"
hyper = "0.13.5"
futures = "0.3.5"
tokio = "0.2.21"
log = "0.4.8"
thiserror = "1.0.19"
anyhow = "1.0.31"
chrono = "0.4.11"
serde = "1.0.110"
regex = "1.3.9"
percent-encoding = "2.1.0"
bb8-redis = { version = "0.5.0", optional = true }
cookie = { version = "0.14.0", features = [] }
bincode = "1.2.1"
rand = "0.7.3"
rand_chacha = "0.2.2"
base64 = "0.12.1"
mime_guess = { version = "2.0.3", optional = true }
hyper-staticfile = { version = "0.5.3", optional = true }

[dev-dependencies]
reign = { path = "../" }
version-sync = "0.9.0"
tokio = { version = "0.2.21", features = ["macros"] }
reqwest = "0.10.4"

[features]
default = []
doc = []
session-redis = ["bb8-redis"]
file-handlers = ["tokio/fs", "mime_guess", "hyper-staticfile"]

[package.metadata.docs.rs]
all-features = true
