base_url = "https://reign.rs"

title = "Reign"
description = "Opinionated Fullstack Web Framework in Rust"

compile_sass = false
highlight_code = true
highlight_theme = "material-light"
build_search_index = true

default_language = "en"

languages = [
	{ code = "ru", search = true },
]

[translations]

[translations.en]
search = "Search"
release = "Release"
language = "Language"
guide = "Guide"
reference = "Reference"
code = "Code"

[translations.ru]
search = "Поиск"
release = "Релиз"
language = "Язык"
guide = "Руководство"
reference = "Ссылка"
code = "Код"

[extra]
releases = [
]
languages = { en = "English", ru = "Pусский" }
