[package]
name = "examples_views_tide"
version = "0.0.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../../reign", features = ["views-tide", "json"], default-features = false }
tide = "0.8"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
test_examples = { path = "../../../development/test_examples" }
