[package]
name = "reign_examples_views_gotham"
version = "0.1.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../../reign", features = ["views-gotham", "json"], default-features = false }
gotham = { git = "git://github.com/gotham-rs/gotham", branch = "master" }
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"

[dev-dependencies]
test_examples = { path = "../../../development/test_examples" }
