[package]
name = "examples_views_warp"
version = "0.0.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../reign", features = ["view-warp", "json"], default-features = false }
warp = "0.2.2"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
test_examples = { path = "../../../reign/development/test_examples" }
