[package]
name = "reign_examples_views_warp"
version = "0.1.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../../reign", features = ["views-warp", "helpers-redirect"], default-features = false }
warp = "0.2"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
reqwest = "0.10"
