[package]
name = "reign_examples_basic"
version = "0.1.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reign = { path = "../../../reign" }
diesel = { version = "1.4.3", features = ["sqlite"] }
gotham = "0.4"
gotham_derive = "0.4"
hyper = "0.12.32"
mime = "0.3.14"
gotham_middleware_diesel = "0.1.0"
futures = "0.1"
