[package]
name = "examples_views_actix"
version = "0.0.0"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reign = { path = "../../../reign", features = ["view-actix", "json"], default-features = false }
actix-web = "3.0.0-alpha.3"
actix-rt = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
test_examples = { path = "../../../reign/development/test_examples" }
