name: CI
on:
  push:
    branches: [master]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
    paths-ignore: ["docs/**"]
jobs:
  ci:
    name: CI
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  test:
    strategy:
      matrix:
        type:
          - test
          - views/actix
          - views/gotham
          - views/normal
          # - views/tide
          - views/warp
          - router/gotham
        rust: [nightly-2020-03-19]
        os: [windows-latest, macos-latest, ubuntu-latest]
        target:
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
        exclude:
          - os: windows-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: i686-pc-windows-msvc
          - os: macos-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-apple-darwin
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Ready cache
        if: matrix.os == 'ubuntu-latest'
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
      - name: Cache cargo
        if: matrix.type == 'test'
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('reign/{Cargo.toml,**/Cargo.toml}') }}
      - name: Test
        if: matrix.type == 'test'
        shell: bash
        run: |
          cd reign
          cargo test --all-features --target ${{ matrix.target }} -- --test-threads 1
      - name: Test Example
        if: matrix.type != 'test'
        shell: bash
        run: |
          if [-d examples/${{ matrix.type }}]; then
            cd examples/${{ matrix.type }}
            cargo test
          fi
      - name: Test Integration
        if: matrix.type != 'test'
        shell: bash
        run: |
          if [-d tests/${{ matrix.type }}]; then
            cd tests/${{ matrix.type }}
            cargo test
          fi
      - name: Install cargo-cache
        uses: actions-rs/install@v0.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          crate: cargo-cache
          use-tool-cache: true
      - name: Cleanup cache
        if: matrix.type == 'test' && steps.cache.outputs.cache-hit != 'true'
        run: cargo cache -a
      # https://github.com/rust-lang/rust/issues/29497
      - name: Cleanup windows cache
        if: matrix.type == 'test' && steps.cache.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'
        shell: bash
        run: |
          rm -rf ~/.cargo/git/checkouts
          rm -rf ~/.cargo/registry/index
