name: Docs
on:
  push:
    branches: [master]
    paths: ["docs/**"]
jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
      - name: Deploy
        if: ${{ success() }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs/public
