name: Docs
on:
  push:
    branches: [master]
    paths: ["docs/**"]
jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: docs
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
