name: Lint
on:
  push:
    branches: [master]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
    paths-ignore: ["docs/**"]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-03-19
          override: true
          components: rustfmt, clippy
      - name: Format check
        run: |
          cd reign
          cargo fmt -- --check
          cargo clippy --all-features -- -D warnings
